name: CD Workflow v2

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
      
jobs:

  ci:
    name: CI Workflow Main
    uses: ./.github/workflows/ci-workflow-v2.yml

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    name: Deploy Heroku
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'sgcmapiteste'
          heroku_email: 'danielnsilva@gmail.com'
